development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  host: ec2-34-233-163-137.compute-1.amazonaws.com
  port: 16419
  password: <%= ENV['SECRET_KEY_BASE'] %>
  # url: redis://localhost:6379/1
  channel_prefix: conntext-api_production
